#!/bin/bash

D="`pwd`"

while true; do
	if [ -d "$D/_git" ]; then
		break
	fi
	if [ -z "${D%/*}" ]; then
		echo cannot find _git
		exit 1
	fi
	D="${D%/*}"
done

GIT_DIR="$D/_git/" GIT_WORK_TREE="$D" git "$@"

