#!/bin/bash

PYTHON=`which python3`
PYTHON_ARGS=
if [ -z "${PYTHON}" ]; then
	# TODO: just detect the platform
	PYTHON="py.exe"
	PYTHON_ARGS="-3"
fi

if [ -z `which readlink` ]; then
	PROXY_PATH="${BASH_SOURCE[0]}"
else
	PROXY_PATH=`readlink -f "${BASH_SOURCE[0]}"`
fi
PROXY_DIR=`dirname "${PROXY_PATH}"`
SCRIPT_PATH="${PROXY_DIR}/kaleido.py"

"${PYTHON}" ${PYTHON_ARGS} "${SCRIPT_PATH}" "$@"

