#!/bin/bash

PYTHON=`which python3`
[ -z "${PYTHON}" ] && PYTHON=`which python`

if [ -z `which readlink` ]; then
	PROXY_PATH="${BASH_SOURCE[0]}"
else
	PROXY_PATH=`readlink -f "${BASH_SOURCE[0]}"`
fi
PROXY_DIR=`dirname "${PROXY_PATH}"`
SCRIPT_PATH="${PROXY_DIR}/kaleido.py"

"${PYTHON}" "${SCRIPT_PATH}" "$@"

